main: com.propr.propressentials.ProprEssentials
name: proprEssentials
version: 0.1
author: propr

commands:
  heal:
    description: Heal and feed yourself
    permission: propressentials.heal
    usage: /heal
  tp:
    description: Teleport you or someone else to another player
    aliases:
      - teleport
    permission: propressentials.tp
    usage: "/tp <Optional: Player1> <Player2>"
  tphere:
    description: Teleport another player to yourself
    permission: propressentials.tphere
    usage: /tphere <Player>
  fly:
    description: Toggle fly mode for yourself
    permission: propressentials.fly
    usage: /fly
  motd:
    description: Show the message of the day
    usage: /motd
  gamemode:
    description: Set your's or someone else's gamemode
    permission: propressentials.gamemode
    usage: "/gamemode <s/c/a/sp> <Optional: Player>"